name: web_1
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  responsive_builder: ^0.7.0
  firebase_core: ^2.29.0
  cloud_firestore: ^4.16.1
  firebase_auth: ^4.19.1
  firebase_core_web: ^2.16.0
  firebase_storage: ^11.7.5
  image_picker: ^1.1.1
  image_picker_for_web: ^3.0.4
  firebase_messaging_web: ^3.8.6
  firebase_messaging: ^14.9.3
  intl: ^0.19.0
  pdf: ^3.6.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  flutter_datetime_picker: ^1.5.1
  file_picker: ^6.2.1
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^3.0.0


flutter:

  
  uses-material-design: true


  assets:
     - assets/images/admin.jpg
     - assets/images/logo.png
     - assets/images/junior.png


  